name: lint-test-deploy
on: push 
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code 
        uses: actions/checkout
      # - name: Install Dependencies 
      #   uses: npm ci 
      # - name: Run Lint 
      #   uses: npm test 
